name: Update Prices Daily

on:
  schedule:
    - cron: "15 5 * * *"  # runs 05:15 UTC daily
  workflow_dispatch:      # lets you run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # needed to commit generated files back to repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Run updater
        run: |
          python prices_updater.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/prices.json docs/prices.csv
          git commit -m "chore: daily prices update" || echo "No changes"
          git push
